name: 'Docker build and push'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mablanco/loki
  GRYPE_VERSION: 0.28.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Grype
        run: |
          cd /tmp
          curl -sSfL https://github.com/anchore/grype/releases/download/v${{ env.GRYPE_VERSION }}/grype_${{ env.GRYPE_VERSION}}_linux_amd64.tar.gz -o grype_linux_amd64.tar.gz
          tar xzvf grype_linux_amd64.tar.gz
          chmod +x grype
          mv -v grype /usr/local/bin/
          echo -n "Installed "
          /usr/local/bin/grype version | grep -i "^version"
          echo "Download the latest vulnerability database..."
          /usr/local/bin/grype db update -v
  
      - name: Scan image for vulnerabilities
        run: /usr/local/bin/grype ${{ steps.meta.outputs.tags }} | tee /tmp/vuln-scan.txt

      - name: Publish image scan results
        uses: actions/upload-artifact@v2
        with:
          name: vuln-scan.txt
          path: /tmp/vuln-scan.txt
          retention-days: 15
